# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Computesphere < Formula
  desc "ComputeSphere's command line tool."
  homepage "https://computesphere.com"
  version "0.0.2-rc"

  on_macos do
    on_intel do
      url "https://github.com/computesphere/cli/releases/download/0.0.2-rc/computesphere_0.0.2-rc_macOS_ amd64.tar.gz"
      sha256 "0d039e43ff53332e7c26605a7e0b69fcd61bd73917ba0b21e18968baad1563f3"

      def install
        bin.install "computesphere"
      end
    end
    on_arm do
      url "https://github.com/computesphere/cli/releases/download/0.0.2-rc/computesphere_0.0.2-rc_macOS_ arm64.tar.gz"
      sha256 "081d563be83a4660338dc5de07e3a6593ecc9e1ad5f8803eb9eea022cb6219f9"

      def install
        bin.install "computesphere"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/computesphere/cli/releases/download/0.0.2-rc/computesphere_0.0.2-rc_linux_ amd64.tar.gz"
        sha256 "a18128a1177bcddff0cc69314a69a62f7ba5dd5d7a349a3af788043a1d4c8a83"

        def install
          bin.install "computesphere"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/computesphere/cli/releases/download/0.0.2-rc/computesphere_0.0.2-rc_linux_ arm_v6.tar.gz"
        sha256 "2c3f9ac81555fd3d43fe72d529ff62465f5be9f837813f08fdad4e70ec2311fa"

        def install
          bin.install "computesphere"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/computesphere/cli/releases/download/0.0.2-rc/computesphere_0.0.2-rc_linux_ arm64.tar.gz"
        sha256 "9c4e251a0745c3b756cf04cfa366696c031c62826bfec57499d838e626cc7503"

        def install
          bin.install "computesphere"
        end
      end
    end
  end
end
