# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Computesphere < Formula
  desc "Command-line tool for ComputeSphere"
  homepage "https://computesphere.com"
  version "0.0.2-rc"

  on_macos do
    on_intel do
      url "https://github.com/computesphere/cli/releases/download/0.0.2-rc/darwin_amd64.tar.gz"
      sha256 "2ee03f9a876337fade5cd4c27ce444cd14c05a2ad385fd807d9d79928bb6673d"

      def install
        bin.install "computesphere"
      end
    end
    on_arm do
      url "https://github.com/computesphere/cli/releases/download/0.0.2-rc/darwin_arm64.tar.gz"
      sha256 "c6c60ebb954f525199dba9240cd00d039f1ce4dec21e867501a3b1e9cf5e3394"

      def install
        bin.install "computesphere"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/computesphere/cli/releases/download/0.0.2-rc/linux_amd64.tar.gz"
        sha256 "a7342af65bf9f8ae1cee1c84612366bd4d32cd4fc29721c91bb7cd92c10066e0"

        def install
          bin.install "computesphere"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/computesphere/cli/releases/download/0.0.2-rc/linux_arm.tar.gz"
        sha256 "664561a7655b576a5956f830f35e0445a378ff6267ab51a3dd220ed939c4a38b"

        def install
          bin.install "computesphere"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/computesphere/cli/releases/download/0.0.2-rc/linux_arm64.tar.gz"
        sha256 "27e307800f228169ca154ed74407cfa95f7ce448faab8d8853d335b3ddca7e52"

        def install
          bin.install "computesphere"
        end
      end
    end
  end
end
