# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Computesphere < Formula
  desc "Command-line tool for ComputeSphere"
  homepage "https://computesphere.com"
  version "0.0.4-rc"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/computesphere/cli/releases/download/0.0.4-rc/darwin_amd64.tar.gz"
      sha256 "a5070c6944c8d1dda849a5ac423ced7f698829fb17868c6899b57c105b68af2b"

      def install
        bin.install "computesphere"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/computesphere/cli/releases/download/0.0.4-rc/darwin_arm64.tar.gz"
      sha256 "426f43c318d87e4fd86f03ef41523afe58a47f8a3cab08e5853c4dbfb37bac3f"

      def install
        bin.install "computesphere"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/computesphere/cli/releases/download/0.0.4-rc/linux_amd64.tar.gz"
        sha256 "9fc7bd2f40e8e7efc2f0c7633f1982ae2dc8022f42d748180ede64ff7902af33"

        def install
          bin.install "computesphere"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/computesphere/cli/releases/download/0.0.4-rc/linux_arm.tar.gz"
        sha256 "c57b801f60e42dd8a6efe199ec7d59ecf26f6959b8e29b98a708d0aafe4f9ef9"

        def install
          bin.install "computesphere"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/computesphere/cli/releases/download/0.0.4-rc/linux_arm64.tar.gz"
        sha256 "245462634ec53e3b8551ecba90639e82cb96067ab978e22b56736a7fa4e34318"

        def install
          bin.install "computesphere"
        end
      end
    end
  end
end
