# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Computesphere < Formula
  desc "Command-line tool for ComputeSphere"
  homepage "https://computesphere.com"
  version "0.0.4-rc"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/computesphere/cli/releases/download/0.0.4-rc/darwin_amd64.tar.gz"
      sha256 "9c8b384ca7828669a113095c2f2ef706f5d215745f8292229de6da2f2442d779"

      def install
        bin.install "computesphere"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/computesphere/cli/releases/download/0.0.4-rc/darwin_arm64.tar.gz"
      sha256 "526e7a9674069ac4cce39022ae4055cd3289bb0bd3cae13a1b67cc43398e0dcf"

      def install
        bin.install "computesphere"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/computesphere/cli/releases/download/0.0.4-rc/linux_amd64.tar.gz"
        sha256 "1095faffff707e946652a3f7ebf3c4c2551794c58ebbe242c51af11fcbf48db9"

        def install
          bin.install "computesphere"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/computesphere/cli/releases/download/0.0.4-rc/linux_arm.tar.gz"
        sha256 "ec58ca98eead6d12ff90ce8bba2579fc0b124d7a44c8b1ae4d712e565c63feaa"

        def install
          bin.install "computesphere"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/computesphere/cli/releases/download/0.0.4-rc/linux_arm64.tar.gz"
        sha256 "8038284ed7c9373fbbdc060755fe657c456b12a469869d6ba25b18d8962a2bb5"

        def install
          bin.install "computesphere"
        end
      end
    end
  end
end
