# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Csph < Formula
  desc "Command-line tool for ComputeSphere"
  homepage "https://computesphere.com"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/computesphere/cli/releases/download/0.5.0/darwin_amd64.tar.gz"
      sha256 "01e0be9c3208a7effd4868f3523a8d931f63fe86399d5ee27933d37380389ee6"

      define_method(:install) do
        bin.install "csph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/computesphere/cli/releases/download/0.5.0/darwin_arm64.tar.gz"
      sha256 "d00829b486309cb4c3110dd447a0240a15e1c00f385c96c140c0122573177943"

      define_method(:install) do
        bin.install "csph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/computesphere/cli/releases/download/0.5.0/linux_amd64.tar.gz"
      sha256 "2c0cdefe990008c8c83dc64754effc9676945527ed59d726ccc7cd10e008b5ea"
      define_method(:install) do
        bin.install "csph"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/computesphere/cli/releases/download/0.5.0/linux_arm.tar.gz"
      sha256 "f53c777d44671ab972b8f9e80c07bc967f0f2fd7ce4b7793e57ef4f38c597da4"
      define_method(:install) do
        bin.install "csph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/computesphere/cli/releases/download/0.5.0/linux_arm64.tar.gz"
      sha256 "35187fc0b7bccc75b4e6ccaf2d0921b51fdfcc6d7a2c1210001bd73b029000c4"
      define_method(:install) do
        bin.install "csph"
      end
    end
  end
end
