# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Csph < Formula
  desc "Command-line tool for ComputeSphere"
  homepage "https://computesphere.com"
  version "0.11.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/computesphere/cli/releases/download/0.11.0/darwin_amd64.tar.gz"
      sha256 "bd6fd591fe61e676954fde6b082c0cb7086ece6fa5c86c5c283798f8f2e8d8f9"

      define_method(:install) do
        bin.install "csph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/computesphere/cli/releases/download/0.11.0/darwin_arm64.tar.gz"
      sha256 "6b04bd2d1b91670e031d921265f9f9b1c8f3a047a1a4c5d629b014bff3b305ba"

      define_method(:install) do
        bin.install "csph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/computesphere/cli/releases/download/0.11.0/linux_amd64.tar.gz"
      sha256 "755fa667687b69e7fb94a272bc6333876351bae0e3a7975dd0a5645e1102d6e4"
      define_method(:install) do
        bin.install "csph"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/computesphere/cli/releases/download/0.11.0/linux_arm.tar.gz"
      sha256 "9f2dbf39c1d407bc945f27915efd9744274104a787ba084d11111370d0569359"
      define_method(:install) do
        bin.install "csph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/computesphere/cli/releases/download/0.11.0/linux_arm64.tar.gz"
      sha256 "e874012904f236896be12c4a63ce6c8bc7f3ba1cbac342e1c64598e56bbc11b2"
      define_method(:install) do
        bin.install "csph"
      end
    end
  end
end
